// frontend/src/views/DnsPlatforms.vue
<template>
  <div class="card">
    <div class="card-title">
      <span>DNS平台配置</span>
      <div class="title-actions">
        <el-input 
          v-model="searchKeyword" 
          placeholder="搜索配置名称、备注..." 
          clearable 
          style="width:220px" 
          size="small"
        >
          <template #prefix>
            <el-icon><Search /></el-icon>
          </template>
        </el-input>
        <el-button size="small" @click="loadData" :loading="loading"><el-icon><Refresh /></el-icon></el-button>
        <el-button type="primary" size="small" @click="openDialog()">添加平台</el-button>
      </div>
    </div>

    <el-table :data="filteredConfigs" stripe class="dns-table">
      <el-table-column label="配置信息" min-width="180">
        <template #default="{ row }">
          <div class="config-name">{{ row.name }}</div>
          <div class="config-meta">
            <el-tag :type="platformTypes[row.platform]?.type || 'info'" size="small">
              {{ platformTypes[row.platform]?.name || row.platform }}
            </el-tag>
            <el-tag v-if="row.is_default === 1" type="warning" size="small">默认</el-tag>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="AccessKey" min-width="220">
        <template #default="{ row }">
          <div class="secret-cell">
            <code class="secret-text">{{ maskValue(row.access_key, showKey[row.id]) }}</code>
            <div class="secret-actions">
              <el-icon class="action-icon" @click="toggleShow(showKey, row.id)">
                <View v-if="!showKey[row.id]" /><Hide v-else />
              </el-icon>
              <el-icon class="action-icon" @click="copyValue(row.access_key, 'AccessKey')">
                <DocumentCopy />
              </el-icon>
            </div>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="SecretKey" min-width="220">
        <template #default="{ row }">
          <div class="secret-cell">
            <code class="secret-text">{{ maskValue(row.secret_key, showSecret[row.id]) }}</code>
            <div class="secret-actions">
              <el-icon class="action-icon" @click="toggleShow(showSecret, row.id)">
                <View v-if="!showSecret[row.id]" /><Hide v-else />
              </el-icon>
              <el-icon class="action-icon" @click="copyValue(row.secret_key, 'SecretKey')">
                <DocumentCopy />
              </el-icon>
            </div>
          </div>
        </template>
      </el-table-column>

      <el-table-column label="标签" min-width="120">
        <template #default="{ row }">
          <div class="tag-list">
            <el-tag v-for="tag in parseTags(row.tags)" :key="tag" :style="getTagStyle(tag)" size="small">{{ tag }}</el-tag>
            <span v-if="!parseTags(row.tags).length" class="empty-text">-</span>
          </div>
        </template>
      </el-table-column>

      <el-table-column prop="remark" label="备注" min-width="120" show-overflow-tooltip />

      <el-table-column prop="created_at" label="创建时间" width="160">
        <template #default="{ row }">
          <span class="time-text">{{ formatDateTime(row.created_at) }}</span>
        </template>
      </el-table-column>

      <el-table-column label="操作" width="170" fixed="right">
        <template #default="{ row }">
          <el-button type="success" size="small" @click="testConfig(row)" :loading="row.testing">测试</el-button>
          <el-dropdown trigger="click" style="margin-left:8px">
            <el-button size="small">更多<el-icon class="el-icon--right"><ArrowDown /></el-icon></el-button>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item @click="setDefault(row)" :disabled="row.is_default === 1">设为默认</el-dropdown-item>
                <el-dropdown-item @click="openDialog(row)">编辑</el-dropdown-item>
                <el-dropdown-item divided @click="handleDelete(row.id)" style="color:#f56c6c">删除</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-table-column>
    </el-table>

    <AppDialog v-model="dialogVisible" :title="form.id ? '编辑DNS平台' : '添加DNS平台'" width="560px" :loading="saving" @confirm="handleSave">
      <el-form :model="form" label-width="120px">
        <el-form-item label="配置名称">
          <el-input v-model="form.name" placeholder="例如: 主账号" />
        </el-form-item>
        <el-form-item label="DNS平台">
          <el-select v-model="form.platform" style="width:100%">
            <el-option v-for="(info, key) in platformTypes" :key="key" :label="info.name" :value="key" />
          </el-select>
        </el-form-item>
        <el-form-item :label="platformTypes[form.platform]?.keyLabel || 'AccessKey'">
          <el-input v-model="form.access_key" placeholder="请输入 AccessKey" />
        </el-form-item>
        <el-form-item :label="platformTypes[form.platform]?.secretLabel || 'SecretKey'">
          <el-input
            v-model="form.secret_key"
            :type="showFormSecret ? 'text' : 'password'"
            :placeholder="form.id ? '留空则不修改' : '请输入 SecretKey'"
            show-password
          />
          <div v-if="form.id && editingOriginalSecret" class="form-tip">
            当前已保存密钥，留空表示不修改
          </div>
        </el-form-item>
        <el-form-item label="备注">
          <el-input v-model="form.remark" type="textarea" :rows="2" placeholder="可选备注" />
        </el-form-item>
        <el-form-item label="标签">
          <el-select v-model="form.tagList" multiple filterable allow-create default-first-option placeholder="选择或输入标签" style="width:100%" @change="onTagChange">
            <el-option v-for="t in dataStore.serverTags" :key="t.id" :label="t.name" :value="t.name" />
          </el-select>
        </el-form-item>
      </el-form>
    </AppDialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Refresh, Search, View, Hide, ArrowDown, DocumentCopy } from '@element-plus/icons-vue'
import { useDataStore } from '@/stores/data'
import { platformTypes } from '@/utils'
import api from '@/api'

const dataStore = useDataStore()
const dialogVisible = ref(false)
const saving = ref(false)
const loading = ref(false)
const searchKeyword = ref('')
const showKey = ref({})
const showSecret = ref({})
const editingOriginalSecret = ref('')
const form = reactive({ id: null, name: '', platform: 'aliyun', access_key: '', secret_key: '', remark: '', tagList: [] })

const filteredConfigs = computed(() => {
  if (!searchKeyword.value) return dataStore.aliyunConfigs
  const kw = searchKeyword.value.toLowerCase()
  return dataStore.aliyunConfigs.filter(c => 
    c.name?.toLowerCase().includes(kw) ||
    c.remark?.toLowerCase().includes(kw) ||
    c.platform?.toLowerCase().includes(kw) ||
    c.access_key?.toLowerCase().includes(kw) ||
    c.tags?.toLowerCase().includes(kw)
  )
})

onMounted(() => {
  loadData()
  dataStore.loadServerTags()
})

async function loadData() {
  loading.value = true
  try {
    await dataStore.loadAliyunConfigs()
  } finally {
    loading.value = false
  }
}

function parseTags(tags) {
  if (!tags) return []
  return tags.split(',').filter(t => t.trim())
}

function getTagColor(tagName) {
  const tag = dataStore.serverTags.find(t => t.name === tagName)
  return tag?.color || ''
}

function getTagStyle(tagName) {
  const color = getTagColor(tagName)
  return color ? { backgroundColor: color, borderColor: color, color: '#fff' } : {}
}

function maskValue(value, visible) {
  if (!value) return '-'
  if (visible) return value
  if (value.length <= 8) return '••••••••'
  return `${value.slice(0, 4)}****${value.slice(-4)}`
}

function toggleShow(target, id) {
  target.value = { ...target.value, [id]: !target.value[id] }
}

async function copyValue(value, label) {
  if (!value) {
    ElMessage.warning(`${label} 为空`)
    return
  }
  try {
    await navigator.clipboard.writeText(value)
    ElMessage.success(`${label} 已复制`)
  } catch {
    ElMessage.error('复制失败')
  }
}

function formatDateTime(value) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return date.toLocaleString('zh-CN', { hour12: false })
}

async function onTagChange(tags) {
  for (const tag of tags) {
    const exists = dataStore.serverTags.some(t => t.name === tag)
    if (!exists) {
      try {
        await api.post('/tags', { name: tag })
        dataStore.loadServerTags()
      } catch (e) {}
    }
  }
}

function openDialog(row = null) {
  if (row) {
    editingOriginalSecret.value = row.secret_key || ''
    Object.assign(form, {
      id: row.id,
      name: row.name,
      platform: row.platform || 'aliyun',
      access_key: row.access_key || '',
      secret_key: row.secret_key || '',
      remark: row.remark || '',
      tagList: parseTags(row.tags)
    })
  } else {
    editingOriginalSecret.value = ''
    const defaultTag = dataStore.serverTags.find(t => t.is_default === 1)
    Object.assign(form, { 
      id: null, name: '', platform: 'aliyun', access_key: '', secret_key: '', remark: '', 
      tagList: defaultTag ? [defaultTag.name] : [] 
    })
  }
  dialogVisible.value = true
}

async function handleSave() {
  if (!form.name.trim()) {
    ElMessage.warning('请输入配置名称')
    return
  }
  if (!form.access_key.trim()) {
    ElMessage.warning('请输入 AccessKey')
    return
  }
  if (!form.id && !form.secret_key.trim()) {
    ElMessage.warning('请输入 SecretKey')
    return
  }

  saving.value = true
  try {
    const data = {
      name: form.name.trim(),
      platform: form.platform,
      access_key: form.access_key.trim(),
      remark: form.remark || '',
      tags: form.tagList.join(',')
    }

    if (form.id) {
      if (form.secret_key.trim()) {
        data.secret_key = form.secret_key.trim()
      }
      await api.put(`/dns/aliyun-configs/${form.id}`, data)
    } else {
      data.secret_key = form.secret_key.trim()
      await api.post('/dns/aliyun-configs', data)
    }

    ElMessage.success('保存成功')
    dialogVisible.value = false
    dataStore.loadAliyunConfigs()
  } finally {
    saving.value = false
  }
}

async function handleDelete(id) {
  await ElMessageBox.confirm('确定删除此配置？', '提示')
  await api.delete(`/dns/aliyun-configs/${id}`)
  ElMessage.success('删除成功')
  dataStore.loadAliyunConfigs()
}

async function setDefault(row) {
  await api.post(`/dns/aliyun-configs/${row.id}/set-default`)
  ElMessage.success('已设为默认')
  dataStore.loadAliyunConfigs()
}

async function testConfig(row) {
  row.testing = true
  try {
    const res = await api.post(`/dns/aliyun-configs/${row.id}/test`)
    res.success ? ElMessage.success(res.message) : ElMessage.error(res.message)
  } finally {
    row.testing = false
  }
}
</script>

<style scoped>
.card {
  background: rgba(255, 255, 255, 0.95);
  padding: 25px;
  border-radius: 16px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
}

.card-title {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 20px;
  padding-bottom: 15px;
  border-bottom: 1px solid #f0f0f0;
  display: flex;
  justify-content: space-between;
  align-items: center;
  color: #303133;
}

.title-actions {
  display: flex;
  align-items: center;
  gap: 10px;
}

.config-name {
  font-weight: 600;
  color: #303133;
  margin-bottom: 6px;
}

.config-meta {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
}

.secret-cell {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.secret-text {
  flex: 1;
  min-width: 0;
  font-size: 12px;
  color: #606266;
  background: #f5f7fa;
  padding: 4px 8px;
  border-radius: 6px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}

.secret-actions {
  display: flex;
  gap: 6px;
  flex-shrink: 0;
}

.action-icon {
  cursor: pointer;
  color: #909399;
  font-size: 16px;
  transition: color 0.2s;
}

.action-icon:hover {
  color: #409eff;
}

.tag-list {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.empty-text,
.time-text {
  color: #909399;
  font-size: 12px;
}

.form-tip {
  margin-top: 6px;
  font-size: 12px;
  color: #909399;
}

:deep(.el-table) {
  border-radius: 10px;
  overflow: hidden;
}

:deep(.el-table th) {
  background: #f8f9fa !important;
  font-weight: 600;
}

@media (max-width: 768px) {
  .card {
    padding: 15px;
    border-radius: 12px;
  }

  .card-title {
    font-size: 16px;
    flex-direction: column;
    align-items: flex-start;
    gap: 10px;
  }

  .title-actions {
    width: 100%;
    flex-wrap: wrap;
  }

  .title-actions .el-input {
    flex: 1;
    min-width: 160px;
  }
}
</style>

// admin/src/pages/DnsPlatforms.jsx
import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Button, Dropdown, Form, Input, Modal, Select, Space, Table, Tag, message } from 'antd'
import { CopyOutlined, EyeInvisibleOutlined, EyeOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons'
import api from '@/api'
import { qk } from '@/api/queryKeys'
import PageCard from '@/components/PageCard'
import { confirmAction, copyText, formatDateTime, platformTypes } from '@/utils'
import { getTagStyle, parseTagList } from '@/utils/server-tag-filter'

function maskValue(value, visible) {
  if (!value) return '-'
  if (visible) return value
  if (value.length <= 8) return '••••••••'
  return `${value.slice(0, 4)}****${value.slice(-4)}`
}

export default function DnsPlatforms() {
  const queryClient = useQueryClient()
  const { data: configs = [], isFetching, refetch } = useQuery({
    queryKey: qk.dnsPlatforms,
    queryFn: () => api.get('/dns/aliyun-configs')
  })
  const { data: tags = [] } = useQuery({
    queryKey: qk.tags,
    queryFn: () => api.get('/tags')
  })
  const [keyword, setKeyword] = useState('')
  const [showKey, setShowKey] = useState({})
  const [showSecret, setShowSecret] = useState({})
  const [testingId, setTestingId] = useState(null)
  const [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form] = Form.useForm()
  const editingId = Form.useWatch('id', form)
  const platform = Form.useWatch('platform', form) || 'aliyun'

  const filtered = useMemo(() => {
    if (!keyword) return configs
    const kw = keyword.toLowerCase()
    return configs.filter((c) =>
      c.name?.toLowerCase().includes(kw)
      || c.remark?.toLowerCase().includes(kw)
      || c.platform?.toLowerCase().includes(kw)
      || c.access_key?.toLowerCase().includes(kw)
      || c.tags?.toLowerCase().includes(kw)
    )
  }, [configs, keyword])

  function openDialog(row) {
    if (row) {
      form.setFieldsValue({
        id: row.id,
        name: row.name,
        platform: row.platform || 'aliyun',
        access_key: row.access_key || '',
        secret_key: row.secret_key || '',
        remark: row.remark || '',
        tagList: parseTagList(row.tags)
      })
    } else {
      const defaultTag = tags.find((t) => t.is_default === 1)
      form.setFieldsValue({
        id: null,
        name: '',
        platform: 'aliyun',
        access_key: '',
        secret_key: '',
        remark: '',
        tagList: defaultTag ? [defaultTag.name] : []
      })
    }
    setOpen(true)
  }

  async function onTagChange(tagNames) {
    for (const tag of tagNames) {
      if (!tags.some((t) => t.name === tag)) {
        try {
          await api.post('/tags', { name: tag })
          queryClient.invalidateQueries({ queryKey: qk.tags })
        } catch {
          // 已有拦截器提示
        }
      }
    }
  }

  async function handleSave() {
    const values = await form.validateFields()
    setSaving(true)
    try {
      const data = {
        name: values.name.trim(),
        platform: values.platform,
        access_key: values.access_key.trim(),
        remark: values.remark || '',
        tags: (values.tagList || []).join(',')
      }
      if (values.id) {
        if (values.secret_key?.trim()) data.secret_key = values.secret_key.trim()
        await api.put(`/dns/aliyun-configs/${values.id}`, data)
      } else {
        data.secret_key = values.secret_key.trim()
        await api.post('/dns/aliyun-configs', data)
      }
      message.success('保存成功')
      setOpen(false)
      queryClient.invalidateQueries({ queryKey: qk.dnsPlatforms })
    } finally {
      setSaving(false)
    }
  }

  async function handleDelete(id) {
    await confirmAction('确定删除此配置？')
    await api.delete(`/dns/aliyun-configs/${id}`)
    message.success('删除成功')
    queryClient.invalidateQueries({ queryKey: qk.dnsPlatforms })
  }

  async function setDefault(row) {
    await api.post(`/dns/aliyun-configs/${row.id}/set-default`)
    message.success('已设为默认')
    queryClient.invalidateQueries({ queryKey: qk.dnsPlatforms })
  }

  async function testConfig(row) {
    setTestingId(row.id)
    try {
      const res = await api.post(`/dns/aliyun-configs/${row.id}/test`)
      res.success ? message.success(res.message) : message.error(res.message)
    } finally {
      setTestingId(null)
    }
  }

  const columns = [
    {
      title: '配置信息',
      minWidth: 180,
      render: (_, row) => (
        <div>
          <div style={{ fontWeight: 600, marginBottom: 6 }}>{row.name}</div>
          <Space size={6} wrap>
            <Tag color={platformTypes[row.platform]?.color}>{platformTypes[row.platform]?.name || row.platform}</Tag>
            {row.is_default === 1 && <Tag color="orange">默认</Tag>}
          </Space>
        </div>
      )
    },
    {
      title: 'AccessKey',
      minWidth: 220,
      render: (_, row) => (
        <Space>
          <code className="secret-text">{maskValue(row.access_key, showKey[row.id])}</code>
          <Button type="text" size="small" icon={showKey[row.id] ? <EyeInvisibleOutlined /> : <EyeOutlined />} onClick={() => setShowKey((s) => ({ ...s, [row.id]: !s[row.id] }))} />
          <Button type="text" size="small" icon={<CopyOutlined />} onClick={() => copyText(row.access_key, 'AccessKey')} />
        </Space>
      )
    },
    {
      title: 'SecretKey',
      minWidth: 220,
      render: (_, row) => (
        <Space>
          <code className="secret-text">{maskValue(row.secret_key, showSecret[row.id])}</code>
          <Button type="text" size="small" icon={showSecret[row.id] ? <EyeInvisibleOutlined /> : <EyeOutlined />} onClick={() => setShowSecret((s) => ({ ...s, [row.id]: !s[row.id] }))} />
          <Button type="text" size="small" icon={<CopyOutlined />} onClick={() => copyText(row.secret_key, 'SecretKey')} />
        </Space>
      )
    },
    {
      title: '标签',
      minWidth: 120,
      render: (_, row) => {
        const list = parseTagList(row.tags)
        if (!list.length) return <span style={{ color: '#909399' }}>-</span>
        return (
          <Space size={4} wrap>
            {list.map((tag) => (
              <Tag key={tag} style={getTagStyle(tag, tags)}>{tag}</Tag>
            ))}
          </Space>
        )
      }
    },
    {
      title: '备注',
      dataIndex: 'remark',
      ellipsis: true,
      minWidth: 120
    },
    {
      title: '创建时间',
      width: 160,
      render: (_, row) => <span style={{ color: '#909399', fontSize: 12 }}>{formatDateTime(row.created_at)}</span>
    },
    {
      title: '操作',
      width: 180,
      fixed: 'right',
      render: (_, row) => (
        <Space size={8}>
          <Button size="small" type="primary" loading={testingId === row.id} onClick={() => testConfig(row)}>测试</Button>
          <Dropdown
            menu={{
              items: [
                { key: 'default', label: '设为默认', disabled: row.is_default === 1, onClick: () => setDefault(row) },
                { key: 'edit', label: '编辑', onClick: () => openDialog(row) },
                { type: 'divider' },
                { key: 'del', label: <span style={{ color: '#ff4d4f' }}>删除</span>, onClick: () => handleDelete(row.id).catch(() => {}) }
              ]
            }}
          >
            <Button size="small">更多</Button>
          </Dropdown>
        </Space>
      )
    }
  ]

  return (
    <PageCard
      title="DNS平台配置"
      extra={(
        <>
          <Input
            size="small"
            allowClear
            placeholder="搜索配置名称、备注..."
            prefix={<SearchOutlined />}
            style={{ width: 220 }}
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
          />
          <Button size="small" icon={<ReloadOutlined />} loading={isFetching} onClick={() => refetch()} />
          <Button type="primary" size="small" onClick={() => openDialog()}>添加平台</Button>
        </>
      )}
    >
      <Table rowKey="id" size="small" columns={columns} dataSource={filtered} pagination={false} scroll={{ x: 1100 }} />
      <Modal
        title={editingId ? '编辑DNS平台' : '添加DNS平台'}
        open={open}
        confirmLoading={saving}
        onOk={handleSave}
        onCancel={() => setOpen(false)}
        destroyOnClose
        width={560}
      >
        <Form form={form} labelCol={{ span: 6 }} initialValues={{ platform: 'aliyun', tagList: [] }}>
          <Form.Item name="id" hidden><Input /></Form.Item>
          <Form.Item name="name" label="配置名称" rules={[{ required: true, message: '请输入配置名称' }]}>
            <Input placeholder="例如: 主账号" />
          </Form.Item>
          <Form.Item name="platform" label="DNS平台">
            <Select options={Object.entries(platformTypes).map(([value, info]) => ({ value, label: info.name }))} />
          </Form.Item>
          <Form.Item name="access_key" label={platformTypes[platform]?.keyLabel || 'AccessKey'} rules={[{ required: true, message: '请输入 AccessKey' }]}>
            <Input placeholder="请输入 AccessKey" />
          </Form.Item>
          <Form.Item
            name="secret_key"
            label={platformTypes[platform]?.secretLabel || 'SecretKey'}
            rules={editingId ? [] : [{ required: true, message: '请输入 SecretKey' }]}
          >
            <Input.Password placeholder={editingId ? '留空则不修改' : '请输入 SecretKey'} />
          </Form.Item>
          {editingId ? <div style={{ margin: '-12px 0 12px 25%', color: '#909399', fontSize: 12 }}>当前已保存密钥，留空表示不修改</div> : null}
          <Form.Item name="remark" label="备注">
            <Input.TextArea rows={2} placeholder="可选备注" />
          </Form.Item>
          <Form.Item name="tagList" label="标签">
            <Select
              mode="tags"
              placeholder="选择或输入标签"
              options={tags.map((t) => ({ value: t.name, label: t.name }))}
              onChange={onTagChange}
            />
          </Form.Item>
        </Form>
      </Modal>
      <style>{`
        .secret-text {
          font-size: 12px;
          color: #606266;
          background: #f5f7fa;
          padding: 4px 8px;
          border-radius: 6px;
          max-width: 160px;
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
          display: inline-block;
          font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        }
      `}</style>
    </PageCard>
  )
}
